pan:
  host: 0.0.0.0           #服务地址
  port: 1234              #服务端口
  name: pan-server        #服务名称

database:
  driver: mysql
  host: localhost         # 数据库主机名
  port: 3306              # 数据库端口号
  username: root          # 数据库用户名
  password: 273150        # 数据库密码
  name: Pan               # 数据库名称
  options:                # 其他可选的数据库连接选项
    - charset=utf8mb4     # 字符集设置
    - parseTime=True      # 启用时间解析
    - loc=Local           # 时间地区设置
