pan:
  host: 0.0.0.0           #服务地址
  port: 1234              #服务端口
  name: pan-server        #服务名称
  defaultpagesize: 10     #最小分页
  maxpagesize: 100        #最大分页

database:
  driver: mysql
  host: localhost         # 数据库主机名
  port: 3306              # 数据库端口号
  username: root          # 数据库用户名
  password: 273150        # 数据库密码
  name: Pan               # 数据库名称
  options:                # 其他可选的数据库连接选项
    - charset=utf8mb4     # 字符集设置
    - parseTime=True      # 启用时间解析
    - loc=Local           # 时间地区设置

# SMTP 配置
smtp:
  host: smtp.qq.com                 # SMTP 服务器地址
  port: 587                         # SMTP 服务器端口
  username: 1737429543@qq.com       # 发件人邮箱用户名
  password: vrescmcdciqnfbjf        # 发件人邮箱密码
  isssl: True

JWTconfig:
  secret: xiaoqi
  issuer: pan-service
  expire: 7200
